name: 'Zoocha Media Text Content'
description: 'Provides Media Text Content component for Zoocha.'
type: 'Feature'

install:
  - linkit
recipes:
  - zr-layout-builder-bundle
  - zr-media-bundle

config:
  strict: false